language: python

dist: xenial

python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest -p no:warnings
  - coverage run -m pytest -p no:warnings

deploy:
  provider: pypi
  user: __token__
  password: ${REQTOKEN}
  skip_cleanup: true
  on:
    python: 3.6
    branch: master

after_script:
  - coveralls

